# Generated by Django 3.1.1 on 2020-09-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название парка')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Парк',
                'verbose_name_plural': 'Парки',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='attraction', verbose_name='Фото аттракционна')),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип ограничения')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя посетителя')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя посетителя')),
                ('age', models.CharField(blank=True, max_length=3, null=True, verbose_name='Возраст посетителя')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='Телефон посетителя')),
                ('height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Рост посетителя')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес посетителя')),
                ('family', models.CharField(blank=True, max_length=50, null=True, verbose_name='Семейное положение посетителя')),
                ('answer_list', models.JSONField(blank=True, null=True, verbose_name='Ответы посетителя')),
                ('visitorType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parks.visitortype', verbose_name='тип посетителя')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors', models.ManyToManyField(to='parks.Visitor', verbose_name='Посетители')),
            ],
        ),
        migrations.CreateModel(
            name='FoodZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название аттракциона')),
                ('rating', models.CharField(max_length=50, verbose_name='Рейтинг')),
                ('altitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='северная широта(°N)')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='восточная долгота(°E)')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks.park', verbose_name='Парк')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название аттракциона')),
                ('rating', models.CharField(max_length=50, verbose_name='Рейтинг')),
                ('extreme', models.CharField(max_length=50, verbose_name='Рейтинг экстримальности аттракциона')),
                ('photo', models.ImageField(blank=True, upload_to='attraction', verbose_name='Фото аттракционна')),
                ('altitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='северная широта(°N)')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='восточная долгота(°E)')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks.park', verbose_name='Парк')),
                ('photo_list', models.ManyToManyField(to='parks.Photo', verbose_name='Фотки')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks.queue', verbose_name='Очередь')),
                ('restrictions', models.ManyToManyField(to='parks.Restriction', verbose_name='Огрничения')),
            ],
        ),
    ]
