# Generated by Django 3.1.1 on 2020-09-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название парка')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Парк',
                'verbose_name_plural': 'Парки',
            },
        ),
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип ограничения')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя посетителя')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст посетителя')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='Телефон посетителя')),
                ('height', models.CharField(max_length=50, verbose_name='Рост посетителя')),
                ('weight', models.CharField(max_length=50, verbose_name='Вес посетителя')),
                ('family', models.CharField(max_length=50, verbose_name='Семейное положение посетителя')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors', models.ManyToManyField(to='parks.Visitor', verbose_name='Посетители')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название аттракциона')),
                ('rating', models.CharField(max_length=50, verbose_name='Рейтинг')),
                ('extreme', models.CharField(max_length=50, verbose_name='Рейтинг экстримальности аттракциона')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks.park', verbose_name='Парк')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks.queue', verbose_name='Очередь')),
                ('restrictions', models.ManyToManyField(to='parks.Restrictions', verbose_name='Огрничения')),
            ],
        ),
    ]
