# Generated by Django 3.1.1 on 2020-09-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodzone',
            name='photo_list',
            field=models.ManyToManyField(to='parks.Photo', verbose_name='Фотки'),
        ),
        migrations.AlterField(
            model_name='foodzone',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название фудкорта'),
        ),
    ]
