# Generated by Django 3.1.1 on 2020-09-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.ImageField(blank=True, upload_to='tmp', verbose_name='Фото аттракционна'),
        ),
    ]
