# Generated by Django 3.1.1 on 2020-09-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_attraction_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='photo',
            field=models.ImageField(blank=True, upload_to='attraction', verbose_name='Фото аттракционна'),
        ),
    ]
