# Generated by Django 3.1.1 on 2020-09-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_auto_20200927_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='price',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='стоимость билета'),
        ),
    ]
