# Generated by Django 3.1.1 on 2020-09-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0004_auto_20200926_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
    ]
