# Generated by Django 3.1.1 on 2020-09-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0005_remove_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('LI', 'LIKE'), ('DI', 'DISLIKE')], default=1, max_length=2, verbose_name='выбор'),
            preserve_default=False,
        ),
    ]
