# Generated by Django 3.1.1 on 2020-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0006_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='attraction', verbose_name='Фото аттракционна')),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='photo_list',
            field=models.ManyToManyField(to='parks.Photo', verbose_name='Фотки'),
        ),
    ]
